// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  double_slice: dynamic(() => import("./DoubleSlice")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text_slice: dynamic(() => import("./TextSlice")),
};
